-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 05:19:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reservation_sr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reservation_sr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reservation_sr` DEFAULT CHARACTER SET utf8 ;
USE `reservation_sr` ;

-- -----------------------------------------------------
-- Table `reservation_sr`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_sr`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `numTel` INT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_sr`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_sr`.`Salle` (
  `idSalle` INT NOT NULL,
  `nomSalle` VARCHAR(45) NULL,
  `surface` VARCHAR(45) NULL,
  `capacité` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_sr`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_sr`.`Profile` (
  `idProfile` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `role` VARCHAR(6) NULL DEFAULT 'user',
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idProfile`, `Client_idClient`),
  INDEX `fk_Profile_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `reservation_sr`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_sr`.`Materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_sr`.`Materiel` (
  `idMateriel` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Salle_idSalle` INT NOT NULL,
  PRIMARY KEY (`idMateriel`, `Salle_idSalle`),
  INDEX `fk_Materiel_Salle1_idx` (`Salle_idSalle` ASC) VISIBLE,
  CONSTRAINT `fk_Materiel_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `reservation_sr`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_sr`.`DateReservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_sr`.`DateReservation` (
  `idDateReservation` INT NOT NULL AUTO_INCREMENT,
  `DateDebut` DATE NULL,
  `DateFin` DATE NULL,
  `Duree` DATE NULL,
  PRIMARY KEY (`idDateReservation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_sr`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_sr`.`Reservation` (
  `idReservation` INT NOT NULL AUTO_INCREMENT,
  `prix` VARCHAR(45) NULL,
  `Client_idClient` INT NOT NULL,
  `Salle_idSalle` INT NOT NULL,
  `DateReservation_idDateReservation` INT NOT NULL,
  PRIMARY KEY (`idReservation`, `Client_idClient`, `Salle_idSalle`, `DateReservation_idDateReservation`),
  INDEX `fk_Reservation_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  INDEX `fk_Reservation_Salle1_idx` (`Salle_idSalle` ASC) VISIBLE,
  INDEX `fk_Reservation_DateReservation1_idx` (`DateReservation_idDateReservation` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `reservation_sr`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `mydb`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_DateReservation1`
    FOREIGN KEY (`DateReservation_idDateReservation`)
    REFERENCES `mydb`.`DateReservation` (`idDateReservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
